import type { LegalDict } from './types';

// English is the source of truth for the legal pages. Every other language in
// this folder is a translation of *this* file, and every other language also
// carries a note saying the English is the binding version — because it is.

export const en: LegalDict = {
  terms: {
    metaTitle: 'Terms of Service',
    metaDesc: 'The terms that govern your use of the Symponia app and website, operated by Boroto Ltd.',
    kicker: 'Legal',
    title: 'Terms of Service',
    updated: 'Last updated: July 2026',
    intro:
      'These Terms of Service (the “Terms”) govern your access to and use of the Symponia mobile application and this website (together, the “Service”). The Service is operated by Boroto Ltd, a company registered in England and Wales (“Boroto”, “we”, “us” or “our”). Please read these Terms carefully. By downloading, accessing or using the Service, you agree to be bound by them. If you do not agree, do not use the Service.',
    sections: [
      {
        h: '1. Who we are and how to contact us',
        blocks: [
          { t: 'p', x: 'The Service is provided by Boroto Ltd, registered in England and Wales. You can contact us at any time at [hello@symponia.io](mailto:hello@symponia.io). Our company registration number and registered office address are set out in our published company filings and are available on request.' },
        ],
      },
      {
        h: '2. Eligibility and age',
        blocks: [
          { t: 'p', x: 'You must be at least **18 years old** to create an account and use Symponia. By using the Service you confirm that you are 18 or over and that you have the legal capacity to enter into these Terms. Symponia is intended for adults and is not designed for or directed at children.' },
        ],
      },
      {
        h: '3. Your account',
        blocks: [
          { t: 'p', x: 'To use certain features you must create an account and sign in. You agree to provide accurate information, to keep your login credentials secure, and to be responsible for all activity that takes place under your account. Tell us promptly at [hello@symponia.io](mailto:hello@symponia.io) if you believe your account has been accessed without your permission. You may delete your account at any time from within the app (Profile tab, Account section, “delete account”).' },
        ],
      },
      {
        h: '4. What Symponia is',
        blocks: [
          { t: 'p', x: 'Symponia is an AI-assisted tool for personal reflection and self-exploration. Its features include:' },
          {
            t: 'ul',
            x: [
              'Three modes: Archetype, My Day and Conversation;',
              'An animal archetype exercise and a synthesis of your results;',
              'Personalised daily reflections;',
              'Session-based access to conversations with the app.',
            ],
          },
          { t: 'p', x: 'We may add, change or remove features from time to time to improve the Service.' },
        ],
      },
      {
        h: '5. Symponia is not a medical or crisis service',
        blocks: [
          { t: 'p', x: 'Symponia is **not a medical, therapeutic, psychiatric, psychological, or counselling service**, and it is not a substitute for professional care. Nothing in the app, and nothing generated by Symponia, is professional advice, diagnosis, or treatment, and it should not be relied on as such.' },
          { t: 'p', x: 'Symponia cannot help in an emergency and does not offer crisis support. **If you are in crisis, or think you may harm yourself or someone else, contact your local emergency services or a qualified professional immediately.** In the UK you can call 999, or contact the Samaritans free on 116 123.' },
        ],
      },
      {
        h: '6. AI-generated content',
        blocks: [
          { t: 'p', x: 'Symponia’s responses are generated by artificial intelligence. AI can be wrong, incomplete, or misleading, and its responses may not suit your situation. You are responsible for how you interpret and act on anything Symponia produces, and you should use your own judgement and seek qualified professional advice where appropriate. We do not warrant that any output is accurate, reliable, or fit for any particular purpose.' },
        ],
      },
      {
        h: '7. Subscriptions, pricing and auto-renewal',
        id: 'tokens',
        blocks: [
          { t: 'p', x: '**Free allowance.** New users receive a limited free allowance so they can try Symponia before subscribing.' },
          { t: 'p', x: '**Symponia Monthly (£12.99 per month).** A subscription provides 350 reflection sessions per calendar month. A fresh allowance of 350 sessions is granted at each renewal; unused sessions do not carry over. Daily reflections are free and do not count against your sessions.' },
          { t: 'p', x: '**Billing and renewal.** Subscriptions are sold and processed by Apple through In-App Purchase and are billed to your Apple ID. Your subscription renews automatically at the then-current price at the end of each billing period unless you cancel at least 24 hours before the period ends. You can manage or cancel your subscription at any time in your Apple ID settings (Settings, your name, Subscriptions). Deleting the app does not cancel your subscription.' },
          { t: 'p', x: '**Payment.** Payment is taken by Apple. We never see or store your payment card details. Prices are shown in the app and may change; we will give notice of price changes as required, and any change will not affect a billing period already paid for.' },
        ],
      },
      {
        h: '8. Cancellation and refunds',
        blocks: [
          { t: 'p', x: 'You can cancel your subscription at any time as described above, and you will keep access until the end of the period you have paid for. Purchases are made through Apple, and refunds are handled by Apple under its policies. For full details, including your statutory rights as a consumer, see our [Refund Policy](/refunds). Nothing in these Terms affects your legal rights under the Consumer Rights Act 2015 or other applicable consumer law.' },
        ],
      },
      {
        h: '9. Acceptable use',
        blocks: [
          { t: 'p', x: 'You agree not to:' },
          {
            t: 'ul',
            x: [
              'use the Service for any unlawful, harmful, or fraudulent purpose;',
              'reverse engineer, decompile, scrape, or attempt to extract the source code, prompts, or models behind the Service, except to the extent this restriction is prohibited by law;',
              'use the Service to harass, abuse, threaten, or harm yourself or others;',
              'misrepresent your identity or age, or use another person’s account without permission;',
              'use bots, scripts, or other automated means to access the Service or generate sessions;',
              'interfere with, disrupt, or attempt to gain unauthorised access to the Service or its systems.',
            ],
          },
          { t: 'p', x: 'We may suspend or terminate access if you breach these Terms or use the Service in a way that risks harm to you, to others, or to us.' },
        ],
      },
      {
        h: '10. Intellectual property',
        blocks: [
          { t: 'p', x: 'The Service, including Symponia’s software, the animal archetype framework, prompts, text, design, and branding, is owned by Boroto Ltd or its licensors and is protected by intellectual property laws. We grant you a limited, personal, non-exclusive, non-transferable, revocable licence to use the Service for your own personal, non-commercial use in accordance with these Terms. You may not copy, distribute, or create derivative works from the Service without our written permission.' },
          { t: 'p', x: 'The reflections and conversations you create are yours. We do not claim ownership of your personal content. You grant us a limited licence to process that content only as needed to operate and provide the Service to you, as described in our [Privacy Policy](/privacy).' },
        ],
      },
      {
        h: '11. Third-party services',
        blocks: [
          { t: 'p', x: 'The Service relies on third parties, including Apple (distribution, sign-in, and payments), Anthropic (the Claude AI that generates responses), and Supabase (secure hosting). Your use of the app is also subject to Apple’s [Licensed Application End User License Agreement](/eula). We are not responsible for third-party services, and their own terms and privacy policies apply to their parts of the experience.' },
        ],
      },
      {
        h: '12. Availability and changes to the Service',
        blocks: [
          { t: 'p', x: 'We aim to keep Symponia available but we do not guarantee that it will be uninterrupted, secure, or error-free. The Service may be unavailable during maintenance or for reasons outside our control, and we may modify, suspend, or discontinue all or part of it. Where we discontinue a paid feature, we will act fairly and in line with your consumer rights.' },
        ],
      },
      {
        h: '13. Suspension and termination',
        blocks: [
          { t: 'p', x: 'You may stop using the Service and delete your account at any time. We may suspend or end your access if you breach these Terms, if required by law, or if continuing to provide the Service to you is not reasonably possible. Sections that by their nature should survive termination (including intellectual property, disclaimers, limitation of liability, and governing law) will continue to apply.' },
        ],
      },
      {
        h: '14. Disclaimers',
        blocks: [
          { t: 'p', x: 'Except for the responsibilities we expressly accept in these Terms and any rights you have under consumer law that cannot be excluded, the Service is provided “as is” and “as available”, and we make no warranties of any kind, whether express or implied, about the Service, its content, or any AI-generated output.' },
        ],
      },
      {
        h: '15. Our liability to you',
        blocks: [
          { t: 'p', x: 'Nothing in these Terms limits or excludes our liability where it would be unlawful to do so. This includes liability for death or personal injury caused by our negligence, for fraud or fraudulent misrepresentation, and for any other liability that cannot be limited or excluded under applicable law, including your statutory rights as a consumer.' },
          { t: 'p', x: 'Subject to the paragraph above, and to the fullest extent permitted by law: we are not liable for loss or damage that was not foreseeable, for loss that arises from your reliance on AI-generated content, or for indirect or consequential loss; and our total liability to you for all claims arising from or connected with the Service in any 12-month period will not exceed the greater of (a) the total amount you paid us or Apple for the Service in that period, or (b) £100. We provide the Service for personal use only and are not liable for business losses.' },
        ],
      },
      {
        h: '16. Indemnity',
        blocks: [
          { t: 'p', x: 'You agree to be responsible for, and to reimburse us for, reasonable losses and costs we suffer that arise from your misuse of the Service or your breach of these Terms, to the extent caused by you. This does not limit your consumer rights.' },
        ],
      },
      {
        h: '17. Changes to these Terms',
        blocks: [
          { t: 'p', x: 'We may update these Terms from time to time, for example to reflect changes to the Service or the law. We will change the “Last updated” date above and, where changes are material, take reasonable steps to bring them to your attention. If you continue to use the Service after the changes take effect, you accept the updated Terms. If you do not agree, you should stop using the Service and may cancel and delete your account.' },
        ],
      },
      {
        h: '18. Governing law and jurisdiction',
        blocks: [
          { t: 'p', x: 'These Terms and any dispute arising out of or in connection with them are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of the courts of England and Wales, except that if you live in another part of the UK you may bring proceedings in your home nation, and consumers keep the protection of the mandatory laws of their country of residence.' },
        ],
      },
      {
        h: '19. General',
        blocks: [
          { t: 'p', x: 'If any part of these Terms is found to be unenforceable, the rest will remain in effect. Our failure to enforce a provision is not a waiver of it. You may not transfer your rights under these Terms without our consent; we may transfer ours where your rights are not adversely affected. These Terms, together with our [Privacy Policy](/privacy), [Refund Policy](/refunds), and the [EULA](/eula), are the entire agreement between you and us regarding the Service.' },
        ],
      },
      {
        h: '20. Contact',
        blocks: [
          { t: 'p', x: 'Questions about these Terms? Email us at [hello@symponia.io](mailto:hello@symponia.io).' },
        ],
      },
    ],
  },

  privacy: {
    metaTitle: 'Privacy Policy',
    metaDesc: 'How Boroto Ltd collects, uses, and protects your personal data when you use Symponia.',
    kicker: 'Legal',
    title: 'Privacy Policy',
    updated: 'Last updated: July 2026',
    intro:
      'This Privacy Policy explains how Boroto Ltd (“Boroto”, “we”, “us” or “our”) collects, uses, shares, and protects your personal data when you use the Symponia app and website. Symponia is a space for private reflection, so we collect as little as we can and we never sell your data.',
    sections: [
      {
        h: '1. Who we are (data controller)',
        blocks: [
          { t: 'p', x: 'Boroto Ltd is the controller of your personal data. We are registered in England and Wales. You can reach us about anything in this policy at [hello@symponia.io](mailto:hello@symponia.io). Our company registration number and registered office address are set out in our published company filings and are available on request.' },
        ],
      },
      {
        h: '2. The personal data we collect',
        blocks: [
          { t: 'p', x: '**Information you give us during onboarding and use:**' },
          {
            t: 'ul',
            x: [
              'your first name and, if you choose to share it, your gender;',
              'your seven animal archetypes and your responses to the attuning questions;',
              'your resonance frequency preference;',
              'the messages and reflections you write in each mode;',
              'your notification preferences and whether you opt in to occasional email updates.',
            ],
          },
          { t: 'p', x: '**Account and technical information:**' },
          {
            t: 'ul',
            x: [
              'account details needed to sign you in and keep your data secure;',
              'your session (token) balance and subscription status;',
              'limited technical and diagnostic information (such as app version and basic device information) used to keep the Service working and secure.',
            ],
          },
          { t: 'p', x: '**Purchase information:** when you subscribe, Apple processes your payment. We receive confirmation of your subscription status from Apple, but we never receive or store your payment card details.' },
          { t: 'p', x: 'Some information is also stored locally on your device (for example your archetypes, preferences, and conversation history in each mode). Local data is removed when you delete the app.' },
          { t: 'p', x: 'Please do not share information you do not want to record, and take particular care with special category information (such as details about your health, beliefs, or sexuality). Where such information appears in what you write, we process it only to provide the Service to you, on the basis of your explicit consent, which you can withdraw by deleting the relevant content or your account.' },
        ],
      },
      {
        h: '3. How and why we use your data, and our lawful bases',
        blocks: [
          { t: 'p', x: 'Under UK and EU data protection law we must have a lawful basis for using your personal data. We rely on the following:' },
          {
            t: 'ul',
            x: [
              '**To perform our contract with you**: to create and run your account, generate personalised Symponia responses, deliver your daily reflection, maintain a session during a conversation, and confirm your subscription with Apple.',
              '**Your consent**: to send push notifications or occasional marketing emails (only if you opt in), and to process any special category information contained in what you write. You can withdraw consent at any time.',
              '**Our legitimate interests**: to keep the Service secure and working, prevent misuse and fraud, and improve reliability, in a way that does not override your rights.',
              '**Legal obligation**: to comply with laws that apply to us, for example around tax and responding to lawful requests.',
            ],
          },
          { t: 'p', x: 'We do not use your data for advertising or ad-targeting, and we do not sell your personal data.' },
        ],
      },
      {
        h: '4. How Symponia uses AI',
        blocks: [
          { t: 'p', x: 'To generate reflective responses, the text you send, along with your first name, gender (if provided), archetypes, and resonance frequency, is sent to Anthropic’s Claude API. This processing is under Zero Data Retention (ZDR) terms: Anthropic does not retain the content of your conversations after generating a response, and does not use it to train or improve its models.' },
          { t: 'p', x: 'Symponia generates content automatically, but it does not make solely automated decisions that produce legal or similarly significant effects about you. Symponia is a reflective tool, not a decision-maker.' },
        ],
      },
      {
        h: '5. Who we share data with',
        blocks: [
          { t: 'p', x: 'We share data only with the service providers who help us run Symponia, each acting under agreements that require them to protect it:' },
          {
            t: 'ul',
            x: [
              '**Anthropic**: provides the Claude AI that generates responses, under Zero Data Retention terms. See [anthropic.com/legal/privacy](https://www.anthropic.com/legal/privacy).',
              '**Supabase**: secure database, authentication, and backend hosting for your account and conversations.',
              '**Apple**: App Store distribution, sign-in, push notification delivery, and in-app purchase processing. Payment details are handled entirely by Apple.',
            ],
          },
          { t: 'p', x: 'We may also disclose data if required by law, to protect the safety, rights, or property of our users or others, or in connection with a business transfer, in which case we will tell you and continue to protect your data.' },
        ],
      },
      {
        h: '6. International transfers',
        blocks: [
          { t: 'p', x: 'Some of our providers (including Anthropic and Apple) process data outside the UK and EEA, including in the United States. Where data is transferred internationally, we rely on appropriate safeguards recognised under UK and EU law, such as the UK International Data Transfer Agreement or Addendum and the European Commission’s Standard Contractual Clauses, together with additional protections where needed. You can ask us for more information about these safeguards.' },
        ],
      },
      {
        h: '7. How long we keep your data',
        blocks: [
          { t: 'p', x: 'We keep your account and conversation history for as long as your account is active. When you delete your account (Profile tab, Account section, “delete account”) or ask us to erase your data, we delete it from our live systems, and it is removed from routine backups within a short period. Content sent to Anthropic is not retained by them under ZDR terms. Local data on your device is removed when you delete the app. We may keep limited information for longer only where the law requires it (for example basic transaction records).' },
          { t: 'p', x: 'If you ask us to delete data associated with your account, we will action your request within 30 days.' },
        ],
      },
      {
        h: '8. How we protect your data',
        blocks: [
          { t: 'p', x: 'We use technical and organisational measures to protect your data, including encryption in transit, access controls, and reputable infrastructure providers. No method of transmission or storage is completely secure, but we work to protect your information and to respond quickly if something goes wrong, including notifying you and the relevant authority where the law requires it.' },
        ],
      },
      {
        h: '9. Your rights',
        id: 'gdpr',
        blocks: [
          { t: 'p', x: 'If you are in the UK or the EEA, you have the following rights over your personal data under the UK GDPR and the EU GDPR:' },
          {
            t: 'ul',
            x: [
              '**Access**: get a copy of the personal data we hold about you;',
              '**Rectification**: have inaccurate data corrected;',
              '**Erasure**: have your data deleted (“right to be forgotten”);',
              '**Restriction**: ask us to limit how we use your data;',
              '**Portability**: receive your data in a portable, machine-readable format;',
              '**Objection**: object to processing based on our legitimate interests;',
              '**Withdraw consent**: at any time, where we rely on your consent, without affecting earlier processing.',
            ],
          },
          { t: 'p', x: 'To exercise any of these rights, email [hello@symponia.io](mailto:hello@symponia.io). We will not charge you or treat you differently for exercising your rights. If you are unhappy with how we handle your data, you can complain to the UK Information Commissioner’s Office ([ico.org.uk](https://ico.org.uk)) or your local supervisory authority in the EEA.' },
        ],
      },
      {
        h: '10. Marketing',
        blocks: [
          { t: 'p', x: 'We only send marketing emails if you have opted in. Every marketing email includes an unsubscribe link, and you can opt out at any time by using it or by emailing [hello@symponia.io](mailto:hello@symponia.io). Opting out of marketing does not affect service messages that are necessary to run your account.' },
        ],
      },
      {
        h: '11. Cookies and the website',
        blocks: [
          { t: 'p', x: 'Our website uses only the cookies and local storage strictly necessary to make the site work and to remember basic preferences. We do not use advertising or cross-site tracking cookies. If we add analytics in future, we will update this policy and, where required, ask for your consent first.' },
        ],
      },
      {
        h: '12. Children',
        blocks: [
          { t: 'p', x: 'Symponia is intended for adults. It is not directed at anyone under 18, and we do not knowingly collect personal data from children. If you believe a child has provided us with personal data, contact us at [hello@symponia.io](mailto:hello@symponia.io) and we will delete it.' },
        ],
      },
      {
        h: '13. Changes to this policy',
        blocks: [
          { t: 'p', x: 'We may update this Privacy Policy from time to time. We will change the “Last updated” date above and, where changes are material, take reasonable steps to bring them to your attention. Continued use of Symponia after changes take effect means you accept the updated policy.' },
        ],
      },
      {
        h: '14. Contact',
        blocks: [
          { t: 'p', x: 'For any privacy question or request, contact our privacy team at [hello@symponia.io](mailto:hello@symponia.io).' },
        ],
      },
    ],
  },

  refunds: {
    metaTitle: 'Refund Policy',
    metaDesc: 'How refunds, cancellations, and your consumer rights work for Symponia subscriptions purchased through the App Store.',
    kicker: 'Legal',
    title: 'Refund Policy',
    updated: 'Last updated: July 2026',
    intro:
      'Symponia is operated by Boroto Ltd. Subscriptions are sold and processed by Apple through In-App Purchase. Because Apple handles the payment, refunds are requested from and decided by Apple under its policies. This page explains how that works and sets out your rights as a consumer. Nothing here limits your statutory rights.',
    sections: [
      {
        h: '1. Trying Symponia for free',
        blocks: [
          { t: 'p', x: 'New users receive a limited free allowance so you can experience Symponia before you decide to subscribe. We encourage you to use it before purchasing.' },
        ],
      },
      {
        h: '2. How to request a refund',
        blocks: [
          { t: 'p', x: 'All purchases are made through your Apple ID, so Apple, not Boroto Ltd, processes refunds. To request one:' },
          {
            t: 'ul',
            x: [
              'go to [reportaproblem.apple.com](https://reportaproblem.apple.com) and sign in with your Apple ID; or',
              'on your device, open Settings, tap your name, then use the purchase history to report a problem.',
            ],
          },
          { t: 'p', x: 'Apple reviews each request against its own criteria and decides whether to grant a refund. We are happy to help where we can, but we cannot issue App Store refunds directly or guarantee Apple’s decision.' },
        ],
      },
      {
        h: '3. Cancelling your subscription',
        blocks: [
          { t: 'p', x: 'You can cancel at any time in your Apple ID settings (Settings, your name, Subscriptions). If you cancel, your subscription will not renew, and you keep access until the end of the period you have already paid for. Cancelling does not by itself trigger a refund for the current period, and unused sessions do not carry over. Deleting the app does not cancel your subscription.' },
        ],
      },
      {
        h: '4. Your rights as a UK or EU consumer',
        blocks: [
          { t: 'p', x: 'If you are a consumer in the UK or the EU, you normally have a 14-day right to cancel a purchase of digital content and receive a refund. However, this right can end once supply of the digital content has begun, where you have given your express consent to that and acknowledged that you lose the right to cancel. When you start a subscription and begin using sessions or daily reflections, digital content is supplied immediately, which may end the 14-day cancellation right for content already provided.' },
          { t: 'p', x: 'None of this removes your legal rights. If the Service is faulty, not as described, or not provided with reasonable care and skill, you may be entitled to a remedy under the Consumer Rights Act 2015 (or equivalent law where you live), regardless of Apple’s standard refund process. If you think this applies to you, contact us and we will help.' },
        ],
      },
      {
        h: '5. Price changes',
        blocks: [
          { t: 'p', x: 'If we change the subscription price, the new price will not apply to a billing period you have already paid for. Where required, Apple will ask you to confirm a price increase before it takes effect; if you do not agree, your subscription will not renew at the new price.' },
        ],
      },
      {
        h: '6. Contact us',
        blocks: [
          { t: 'p', x: 'If you have a problem with a payment, a subscription, or the Service, email [hello@symponia.io](mailto:hello@symponia.io) and we will do our best to put it right.' },
        ],
      },
    ],
  },

  eula: {
    metaTitle: 'End User License Agreement',
    metaDesc: 'Apple-standard EULA for the Symponia iOS app. Governs your license to use the Symponia application downloaded from the App Store.',
    kicker: 'Legal',
    titleL1: 'Licensed Application',
    titleL2: 'End User License Agreement',
    sub: 'Apple Standard EULA',
    note: '',
  },

  credits: {
    metaTitle: 'Pricing',
    metaDesc: 'Symponia pricing: start with a free allowance, then £12.99 a month for 350 reflection sessions.',
    kicker: 'Pricing',
    h1: 'Choose your depth',
    lead: 'Start free. Go monthly when you’re ready.',
    free: {
      k: 'New arrivals',
      price: 'Free',
      sub: 'A small free allowance to explore Symponia',
      body: 'Name your seven animal archetypes, receive your constellation portrait, and try a few reflection sessions. No commitment.',
      cta: 'Download on the App Store',
    },
    monthly: {
      badge: 'Recommended',
      k: 'Symponia Monthly',
      sub: 'per month · 350 reflection sessions',
      bullets: [
        '350 sessions across Archetype, My Day, and Conversation modes',
        'Free daily reflections (they don’t count against sessions)',
        'Fresh allotment each month — sessions do not carry over',
        'Cancel anytime via Apple ID settings',
      ],
      cta: 'Available in the app',
    },
    how: {
      h2: 'How it works',
      items: [
        { t: 'One session per reflection', d: 'Each back-and-forth with Symponia uses one session. Daily reflections are free and do not count toward your allotment.' },
        { t: 'Monthly resets', d: 'Your 350 monthly sessions reset at each renewal. Unused sessions do not carry over.' },
        { t: 'Purchase inside the app', d: 'All purchases happen inside the Symponia iOS app via Apple In-App Purchase.' },
        { t: 'Secure payment via Apple', d: 'All payments are processed by Apple. We never see or store your card details.' },
      ],
    },
    contact: 'Questions about subscriptions or billing? Contact us at [hello@symponia.io](mailto:hello@symponia.io). See our [Terms of Service](/terms#tokens) for full details.',
  },
};
